<?php

namespace ECE\Bundle\NetagoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function getVideoPublications()
    {
        return $this->getByCategoryType('Video');
    }

    public function getMusicPublications()
    {
        return $this->getByCategoryType('Music');
    }

    private function getByCategoryType($type)
    {
        $q = $this
            ->createQueryBuilder('p')
            ->select('p, l, c')
            ->leftJoin('p.knownLink', 'l')
            ->leftJoin('l.category', 'c')
            ->where('c.type = :type')
            ->orderBy('p.publishedAt', 'desc')
            ->setParameter('type', $type)
            ->getQuery()
        ;

        return $q->getResult();
    }
}