<?php

namespace ECE\Bundle\NetagoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    
    public function findAllPublicationsByCategory($cat_type)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p 
                                   FROM ECENetagoraBundle:Publication p 
                                   JOIN ECENetagoraBundle:KnownLink')
                    ->getResult();
    }
}