imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

swiftmailer:
    disable_delivery: true

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

madalynn_plum:
    options:
        dry_run: false
        rsync_exclude: "%kernel.root_dir%/config/rsync_exclude.txt"
        commands:
            - 'php app/console cache:clear --env=prod --no-debug'
            - 'php app/console assets:install web'
    deployers:
        - Plum\Deployer\RsyncDeployer
        - Plum\Deployer\SshDeployer
    servers: "%kernel.root_dir%/config/deployment.yml"