ECE\Bundle\NetagoraBundle\Entity\Category:
  type: entity
  repositoryClass: ECE\Bundle\NetagoraBundle\Entity\CategoryRepository
  table: na_categories
  fields:
    id:
      type: integer
      id: true
      generator:      { strategy: AUTO }
    type:             { type: string, length: 40 }
    isDisplayed:      { type: boolean, column: is_displayed }
  lifecycleCallbacks: {  }
  oneToMany:
    knownLinks:
      targetEntity:   KnownLink
      mappedBy:       category
      cascade:        ["persist", "delete", "merge"]
