ECE\Bundle\NetagoraBundle\Entity\PasswordRequest:
  type: entity
  repositoryClass: ECE\Bundle\NetagoraBundle\Entity\PasswordRequestRepository
  table: na_password_requests
  fields:
    id:         { type: integer, id: true, generator: { strategy: AUTO } }
    username:   { type: string, length: 20 }
    token:      { type: string, length: 32, unique: true }
    expiresAt:  { type: datetime, column: expires_at }
  manyToOne:
    user:       { targetEntity: User } 