ECE\Bundle\NetagoraBundle\Entity\Publication:
  type: entity
  repositoryClass: ECE\Bundle\NetagoraBundle\Entity\PublicationRepository
  table: na_publications
  fields:
    id:
      type: integer
      id: true
      generator:         { strategy: AUTO }
    socialNetwork:       { type: string, length: 10, column: social_network, nullable: true }
    author:              { type: string, length: 50 }
    publishedAt:         { type: datetime, column: published_at }
    reference:           { type: string, length: 200 }
    content:             { type: text }
    linkUrl:             { type: string, length: 200, column: link_url }
    isFavorite:          { type: boolean, column: is_favorite }
  lifecycleCallbacks:    {}
  manyToOne:
    user:
      targetEntity: User
      inversedBy:   publications
      cascade:      ["persist", "delete", "merge"]
  oneToOne:
    knownLink:
      targetEntity: KnownLink
      joinColumn:
        name: known_link_id
        referencedColumnName: id
