<?php

namespace ECE\netagoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbRepository extends EntityRepository
{
}