<?php

namespace ECE\netagoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Known_linkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Known_linkRepository extends EntityRepository
{
}