<?php

namespace ECE\netagoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Publication_historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Publication_historyRepository extends EntityRepository
{
}